### ISSUE TITLE
Room 패키지 테스트 실패 이슈

### ISSUE THREAD

**Issue by kimziou77** [prgrms-be-devcourse/BEDV2_Amabnb#44]
## **버그설명**
Room 패키지 테스트 실패 현상

## **재현방법**
전체 패키지 테스트를 돌려본다
room 패키지 테스트를 돌려본다

## **예상결과**
테스트 전체 통과

## **실제 결과**
테스트 일부 실패

## **스크린샷**
전체 패키지 테스트 돌렸을 때
![image](https://user-images.githubusercontent.com/41179265/175793145-b25ee51b-38cc-46a2-ad10-28ca61299200.png)

![image](https://user-images.githubusercontent.com/41179265/175793154-96a8dc74-8fad-4934-b786-971e7fa355cc.png)
![image](https://user-images.githubusercontent.com/41179265/175793165-a8671a31-dc9b-4e07-a817-b972aed56ce7.png)

room 패키지만 테스트 돌렸을 때
![image](https://user-images.githubusercontent.com/41179265/175793203-195fe274-f8f1-4973-a2ac-d87931f96964.png)

**Comment by kimziou77** [comment]
@yongsu-kang

**Comment by yuminhwan** [comment]
필드에 userId가 있지만 생성자에서 받아주지 못해서 나오는 문제같아요! 이부분은 시큐리티 통합하면서 바꿔야할 문제 같습니다!
