### ISSUE TITLE
CI 설정을 한다. 

### ISSUE THREAD

**Issue by yuminhwan** [prgrms-be-devcourse/BEDV2_Amabnb#84]
## 개요
- CI 설정을 한다. 

## 설명
- 젠킨스, 깃허브 연동 (완) 
- RDS 설정
  - mysql로 전환 과정 필요할 듯 
- 빌드 스크립트 작성 ( 실행중인 프로그램 종료 및 빌드한 jar 실행 ) 
- jacoco 설정?
- 프로파일 및 환경변수 설정
- 로그백 설정

**Comment by kimziou77** [comment]
#96
